### ISSUE TITLE
How can I integrate this to my current bot?

### ISSUE THREAD

**Issue by swassapparel1** [MillenniumEarl/recaptcha-harvester#167]
Hi, just wanted to ask how can I integrate this to my current bot? Would really love to collaborate with you guys. Thank you!

**Comment by MillenniumEarl** [comment]
To integrate the form you can follow the instructions in the "[Usage](https://github.com/MillenniumEarl/recaptcha-harvester/blob/444fb90534636cf52245b1a239e8e15a94321382/README.md?plain=1#L28-L48)" section of the README.

Also remember that:

- This module **does not automatically** solve Captchas but requires human intervention, so it is not efficient for automation on multiple pages
- **Electron is required** for this to work and that means developing a client and not a server application
